sudo: required
services:
  - docker

before_install:
  - docker build -t subhre/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true subhre/docker-react npm run test -- --coverage

deploy:
  provide: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-058053867530"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
